version: '3.1'
# Servicios
services:

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portal:
    image: nginx
    container_name: Portal
    restart: always
    environment:
      - VIRTUAL_HOST=portal-antonio.ddns.net
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro