version: '3.1'
# Servicios
services:

  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - LETSENCRYPT_HOST=portal2-antonio.ddns.net
      - LETSENCRYPT_EMAIL=itoaa@hotmail.com
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: 'Lets-Encrypt'
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=Reverse-Proxy
      - VIRTUAL_HOST=portal2-antonio.ddns.net
      - VIRTUAL_PATH=/.well-known
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portal:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=portal2-antonio.ddns.net
      - VIRTUAL_PATH=/
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=portal2-antonio.ddns.net
      - LETSENCRYPT_EMAIL=itoaa@hotmail.com
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro